name: movie_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.6
  curved_navigation_bar: ^1.0.3
  dio: ^5.4.0
  firebase_auth: ^4.15.1
  firebase_core: ^2.24.1
  flutter:
    sdk: flutter
  flutter_firebase_chat_core: ^1.6.7
  get_it: ^7.6.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
