// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5DBtl5_LsY6zMJIy34e-r3VntusUa9IA',
    appId: '1:795629668481:web:c2ccf20727e8b302562580',
    messagingSenderId: '795629668481',
    projectId: 'movie-app-c249d',
    authDomain: 'movie-app-c249d.firebaseapp.com',
    storageBucket: 'movie-app-c249d.appspot.com',
    measurementId: 'G-CEG70L3MN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnI2BWiUj7c1jAUfr8w_ARa03aZ6apqLc',
    appId: '1:795629668481:android:69f00b8789d0eef9562580',
    messagingSenderId: '795629668481',
    projectId: 'movie-app-c249d',
    storageBucket: 'movie-app-c249d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFalRBI3pt75ushIian5ypDtofd6Z8R4',
    appId: '1:795629668481:ios:cacf58dfd69f7a39562580',
    messagingSenderId: '795629668481',
    projectId: 'movie-app-c249d',
    storageBucket: 'movie-app-c249d.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPFalRBI3pt75ushIian5ypDtofd6Z8R4',
    appId: '1:795629668481:ios:88ab96066e7d2357562580',
    messagingSenderId: '795629668481',
    projectId: 'movie-app-c249d',
    storageBucket: 'movie-app-c249d.appspot.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
